# Generated by Django 3.2.2 on 2021-05-13 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_claim_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='files',
        ),
        migrations.AddField(
            model_name='claimfile',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.claim'),
        ),
    ]
