# Generated by Django 3.2.2 on 2021-05-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210513_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimfile',
            name='claim',
        ),
        migrations.AddField(
            model_name='claim',
            name='files',
            field=models.ManyToManyField(limit_choices_to={'claim': 'self'}, related_name='claim', to='app.ClaimFile'),
        ),
    ]
