# Generated by Django 3.2.2 on 2021-05-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210513_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='files',
            field=models.ManyToManyField(limit_choices_to={models.Q(('name__istartswith', '<django.db.models.fields.UUIDField>'))}, related_name='claim', to='app.ClaimFile'),
        ),
    ]
