# Generated by Django 3.2.2 on 2021-05-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_claim_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='files',
            field=models.ManyToManyField(related_name='claim', to='app.ClaimFile'),
        ),
    ]
