# Generated by Django 3.2.3 on 2021-05-17 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_claim_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitexAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=56, null=True)),
                ('exchange', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=32, null=True)),
                ('wallet', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=32, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=32, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='claim',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
